<?php
 
    /* Sản phẩm */
    $nametype = "van-ban";
    $config['product'][$nametype]['title_main'] = "Điều luật";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = true;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = true;
    $config['product'][$nametype]['danhmuc_cap'] = true;
    $config['product'][$nametype]['chidan'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm (Màu) */
    $config['product'][$nametype]['mau_images'] = false;
    $config['product'][$nametype]['mau_mau'] = true;
    $config['product'][$nametype]['mau_loai'] = false;
    $config['product'][$nametype]['width_mau'] = 30;
    $config['product'][$nametype]['height_mau'] = 30;
    $config['product'][$nametype]['thumb_mau'] = '100x100x1';
    $config['product'][$nametype]['img_type_mau'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

     /* Sản phẩm (Cat) */
     $config['product'][$nametype]['title_main_danhmuc'] = "Bộ luật";
     $config['product'][$nametype]['images_danhmuc'] = false;
     $config['product'][$nametype]['show_images_danhmuc'] = false;
     $config['product'][$nametype]['slug_danhmuc'] = true;
     $config['product'][$nametype]['list_danhmuc'] = true;
     $config['product'][$nametype]['sohieu_danhmuc'] = true;
     $config['product'][$nametype]['coquanbanhanh_danhmuc'] = true;
     $config['product'][$nametype]['ngaybanhanh_danhmuc'] = true;
     $config['product'][$nametype]['ngayhethieuluc_danhmuc'] = true;
     $config['product'][$nametype]['sochidanmucdieu_danhmuc'] = true;
     $config['product'][$nametype]['sochidanmuckhoan_danhmuc'] = true;
     $config['product'][$nametype]['sodieumuckhoan_danhmuc'] = true;
     $config['product'][$nametype]['tinhtranghieuluc_danhmuc'] = true;
     $config['product'][$nametype]['nguoiki_danhmuc'] = true;
     $config['product'][$nametype]['linhvuc_danhmuc'] = true;
     $config['product'][$nametype]['tongsodieu_danhmuc'] = true;
     $config['product'][$nametype]['taptin_danhmuc'] = true;
     $config['product'][$nametype]['check_danhmuc'] = array('noibat' => 'Nổi bật');
     $config['product'][$nametype]['mota_danhmuc'] = true;
     $config['product'][$nametype]['mota_cke_danhmuc'] = true;
     $config['product'][$nametype]['noidung_danhmuc'] = true;
     $config['product'][$nametype]['noidung_cke_danhmuc'] = true;
     $config['product'][$nametype]['seo_danhmuc'] = true;
     $config['product'][$nametype]['width_danhmuc'] = 636;
     $config['product'][$nametype]['height_danhmuc'] = 318;
     $config['product'][$nametype]['thumb_danhmuc'] = '636x318x1';
     $config['product'][$nametype]['img_type_danhmuc'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
     $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (Cat) */
    $config['product'][$nametype]['title_main_danhmuc_cap'] = "Chương";
    $config['product'][$nametype]['images_danhmuc_cap'] = true;
    $config['product'][$nametype]['show_images_danhmuc_cap'] = false;
    $config['product'][$nametype]['slug_danhmuc_cap'] = true;
    $config['product'][$nametype]['danhmuc_cap'] = true;
    $config['product'][$nametype]['check_danhmuc_cap'] = array();
    $config['product'][$nametype]['mota_danhmuc_cap'] = false;
    $config['product'][$nametype]['mota_cke_danhmuc_cap'] = false;
    $config['product'][$nametype]['noidung_danhmuc_cap'] = true;
    $config['product'][$nametype]['noidung_cke_danhmuc_cap'] = true;
    $config['product'][$nametype]['seo_danhmuc_cap'] = true;
    $config['product'][$nametype]['width_danhmuc_cap'] = 636;
    $config['product'][$nametype]['height_danhmuc_cap'] = 318;
    $config['product'][$nametype]['thumb_danhmuc_cap'] = '636x318x1';
    $config['product'][$nametype]['img_type_danhmuc_cap'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
 
    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm (Cat) */
    $config['product'][$nametype]['title_main_cat'] = "Sản phẩm cấp 2";
    $config['product'][$nametype]['images_cat'] = true;
    $config['product'][$nametype]['show_images_cat'] = false;
    $config['product'][$nametype]['slug_cat'] = true;
    $config['product'][$nametype]['check_cat'] = array();
    $config['product'][$nametype]['mota_cat'] = false;
    $config['product'][$nametype]['mota_cke_cat'] = false;
    $config['product'][$nametype]['noidung_cat'] = false;
    $config['product'][$nametype]['noidung_cke_cat'] = false;
    $config['product'][$nametype]['seo_cat'] = true;
    $config['product'][$nametype]['width_cat'] = 636;
    $config['product'][$nametype]['height_cat'] = 318;
    $config['product'][$nametype]['thumb_cat'] = '636x318x1';
    $config['product'][$nametype]['img_type_cat'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm (Item) */
    $config['product'][$nametype]['title_main_item'] = "Sản phẩm cấp 3";
    $config['product'][$nametype]['images_item'] = false;
    $config['product'][$nametype]['show_images_item'] = false;
    $config['product'][$nametype]['slug_item'] = true;
    $config['product'][$nametype]['check_item'] = array();
    $config['product'][$nametype]['mota_item'] = false;
    $config['product'][$nametype]['seo_item'] = true;
    $config['product'][$nametype]['width_item'] = 300;
    $config['product'][$nametype]['height_item'] = 200;
    $config['product'][$nametype]['thumb_item'] = '100x100x1';
    $config['product'][$nametype]['img_type_item'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm (Sub) */
    $config['product'][$nametype]['title_main_sub'] = "Sản phẩm cấp 4";
    $config['product'][$nametype]['images_sub'] = true;
    $config['product'][$nametype]['show_images_sub'] = true;
    $config['product'][$nametype]['slug_sub'] = true;
    $config['product'][$nametype]['check_sub'] = array("noibat" => "Nổi bật");
    $config['product'][$nametype]['mota_sub'] = true;
    $config['product'][$nametype]['seo_sub'] = true;
    $config['product'][$nametype]['width_sub'] = 300;
    $config['product'][$nametype]['height_sub'] = 200;
    $config['product'][$nametype]['thumb_sub'] = '100x100x1';
    $config['product'][$nametype]['img_type_sub'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    // /* Sản phẩm (Hãng) */
    // $config['product'][$nametype]['title_main_brand'] = "Hãng sản phẩm";
    // $config['product'][$nametype]['images_brand'] = false;
    // $config['product'][$nametype]['show_images_brand'] = false;
    // $config['product'][$nametype]['slug_brand'] = false;
    // $config['product'][$nametype]['check_brand'] = array();
    // $config['product'][$nametype]['seo_brand'] = false;
    // $config['product'][$nametype]['width_brand'] = 150;
    // $config['product'][$nametype]['height_brand'] = 150;
    // $config['product'][$nametype]['thumb_brand'] = '100x100x1';
    // $config['product'][$nametype]['img_type_brand'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Thư viện ảnh */
    /*$nametype = "thu-vien-anh";
    $config['product'][$nametype]['title_main'] = "Thư viện ảnh";
    $config['product'][$nametype]['check'] = array();
    $config['product'][$nametype]['view'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['images'] = true;
    $config['product'][$nametype]['show_images'] = true;
    $config['product'][$nametype]['gallery'] = array
    (
        $nametype => array
        (
            "title_main_photo" => "Hình ảnh thư viện ảnh",
            "title_sub_photo" => "Hình ảnh",
            "number_photo" => 2,
            "images_photo" => true,
            "avatar_photo" => true,
            "tieude_photo" => true,
            "width_photo" => 540,
            "height_photo" => 540,
            "thumb_photo" => '100x100x1',
            "img_type_photo" => '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF'
        )
    );
    $config['product'][$nametype]['seo'] = true;
    $config['product'][$nametype]['width'] = 270;
    $config['product'][$nametype]['height'] = 270;
    $config['product'][$nametype]['thumb'] = '100x100x1';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';*/

    /* Sản phẩm */
    $nametype = "van-ban-ks";
    $config['product'][$nametype]['title_main'] = "Văn bản ngành KS";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm */
    $nametype = "van-ban-dang";
    $config['product'][$nametype]['title_main'] = "Văn bản của đảng";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';


    /* Sản phẩm */
    $nametype = "van-ban-nb";
    $config['product'][$nametype]['title_main'] = "Văn bản nội bộ";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['donvi'] = true;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['donvi_list'] = true;
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm */
    $nametype = "he-thong-bieu-mau";
    $config['product'][$nametype]['title_main'] = "Hệ thống biểu mẫu";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

    /* Sản phẩm */
    $nametype = "tinh-huong-phap-ly";
    $config['product'][$nametype]['title_main'] = "Tình huống pháp lý";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = false;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';


    /* Sản phẩm */
    $nametype = "phonghop-khonggiay";
    $config['product'][$nametype]['title_main'] = "Phòng họp không giấy";
    $config['product'][$nametype]['dropdown'] = true;
    $config['product'][$nametype]['list'] = true;
    $config['product'][$nametype]['cat'] = false;
    $config['product'][$nametype]['item'] = false;
    $config['product'][$nametype]['sub'] = false;
    $config['product'][$nametype]['brand'] = false;
    $config['product'][$nametype]['danhmuc'] = false;
    $config['product'][$nametype]['danhmuc_cap'] = false;
    $config['product'][$nametype]['chidan'] = false;
    $config['product'][$nametype]['taptin'] = true;
    $config['product'][$nametype]['mau'] = false;
    $config['product'][$nametype]['size'] = false;
    $config['product'][$nametype]['doday'] = false;
    $config['product'][$nametype]['muavu'] = false;
    $config['product'][$nametype]['loaivai'] = false;
    $config['product'][$nametype]['chatlieu'] = false;
    $config['product'][$nametype]['donvi'] = true;
    $config['product'][$nametype]['cauhoi'] = false;
    $config['product'][$nametype]['tags'] = false;
    $config['product'][$nametype]['import'] = false;
    $config['product'][$nametype]['export'] = false;
    $config['product'][$nametype]['view'] = false;
    $config['product'][$nametype]['copy'] = true;
    $config['product'][$nametype]['copy_image'] = true;
    $config['product'][$nametype]['slug'] = true;
    $config['product'][$nametype]['check'] = array('noibat' => 'Nổi bật');
    $config['product'][$nametype]['images'] = false;
    $config['product'][$nametype]['show_images'] = false;
    $config['product'][$nametype]['gallery'] = array();
    $config['product'][$nametype]['ma'] = false;
    $config['product'][$nametype]['gia'] = false;
    $config['product'][$nametype]['giamoi'] = false;
    $config['product'][$nametype]['giakm'] = false;
    $config['product'][$nametype]['ngaybanhanh'] = false;
    $config['product'][$nametype]['tenvuan'] = false;
    $config['product'][$nametype]['nguoiki'] = false;
    $config['product'][$nametype]['nguoiluu'] = false;
    $config['product'][$nametype]['coquanbanhanh'] = false;
    $config['product'][$nametype]['sohieu'] = false;
    $config['product'][$nametype]['linhvuc'] = false;
    $config['product'][$nametype]['motangan'] = false;
    $config['product'][$nametype]['motangan_cke'] = true;
    $config['product'][$nametype]['mota'] = false;
    $config['product'][$nametype]['mota_cke'] = false;
    $config['product'][$nametype]['noidung'] = true;
    $config['product'][$nametype]['noidung_cke'] = true;
    $config['product'][$nametype]['seo'] = false;
    $config['product'][$nametype]['faq'] = false;
    $config['product'][$nametype]['width'] = 900;
    $config['product'][$nametype]['height'] = 900;
    $config['product'][$nametype]['thumb'] = '100x100x2';
    $config['product'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';
    $config['product'][$nametype]['file_type'] = 'doc|docx|pdf|rar|zip|ppt|pptx|DOC|DOCX|PDF|RAR|ZIP|PPT|PPTX|xls|jpg|png|gif|JPG|PNG|GIF|xls|XLS';

    /* Sản phẩm (List) */
    $config['product'][$nametype]['title_main_list'] = "Sản phẩm cấp 1";
    $config['product'][$nametype]['images_list'] = false;
    $config['product'][$nametype]['show_images_list'] = false;
    $config['product'][$nametype]['slug_list'] = true;
    $config['product'][$nametype]['check_list'] = array();
    $config['product'][$nametype]['donvi_list'] = true;
    $config['product'][$nametype]['mota_list'] = false;
    $config['product'][$nametype]['mota_cke_list'] = false;
    $config['product'][$nametype]['noidung_list'] = false;
    $config['product'][$nametype]['noidung_cke_list'] = true;
    $config['product'][$nametype]['seo_list'] = true;
    $config['product'][$nametype]['width_list'] = 300;
    $config['product'][$nametype]['height_list'] = 300;
    $config['product'][$nametype]['thumb_list'] = '100x100x2';
    $config['product'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.JPG|.PNG|.JPEG|.Png|.GIF';

?>